// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_damage_dealer_copper = "CgkIv6KQjKwJEAIQCw"; // <GPGSID>
        public const string achievement_damage_dealer_gold = "CgkIv6KQjKwJEAIQDQ"; // <GPGSID>
        public const string achievement_what_is_that = "CgkIv6KQjKwJEAIQBA"; // <GPGSID>
        public const string achievement_immortel = "CgkIv6KQjKwJEAIQBw"; // <GPGSID>
        public const string achievement_invicible = "CgkIv6KQjKwJEAIQBg"; // <GPGSID>
        public const string achievement_like_rambo = "CgkIv6KQjKwJEAIQCA"; // <GPGSID>
        public const string achievement_damage_dealer_silver = "CgkIv6KQjKwJEAIQDA"; // <GPGSID>
        public const string achievement_logged = "CgkIv6KQjKwJEAIQCQ"; // <GPGSID>
        public const string leaderboard_soul_leaderboard = "CgkIv6KQjKwJEAIQDw"; // <GPGSID>
        public const string achievement_damage_dealer_diamond = "CgkIv6KQjKwJEAIQDg"; // <GPGSID>
        public const string achievement_team_fruit = "CgkIv6KQjKwJEAIQBQ"; // <GPGSID>

}

